### ISSUE TITLE
Frame vs Stride

### ISSUE THREAD

**Issue by StuartIanNaylor** [linto-ai/linto-desktoptools-hmg#4]
Just wondering if half the frame size is correct?

https://haythamfayek.com/2016/04/21/speech-processing-for-machine-learning.html

> Framing
> After pre-emphasis, we need to split the signal into short-time frames. The rationale behind this step is that frequencies in a signal change over time, so in most cases it doesn’t make sense to do the Fourier transform across the entire signal in that we would lose the frequency contours of the signal over time. To avoid that, we can safely assume that frequencies in a signal are stationary over a very short period of time. Therefore, by doing a Fourier transform over this short-time frame, we can obtain a good approximation of the frequency contours of the signal by concatenating adjacent frames.
> 
> Typical frame sizes in speech processing range from 20 ms to 40 ms with 50% (+/-10%) overlap between consecutive frames. Popular settings are 25 ms for the frame size, frame_size = 0.025 and a 10 ms stride (15 ms overlap), frame_stride = 0.01.

Librosa terminology seems to be 
n_fft=2048
hop_length=512

Where frame (n_fft) & stride (hop_length) is 4:1 so guess they are overlapping half a window each side?

Is a 2:1 window:stride correct or should it have some overlap?

**Comment by Lokhozt** [comment]
Hello,
I think there is a terminology confusion here. There are 2 window/frame parameters: window size/length and window hop/stride.
Window length is the size of the signal on witch the analysis is done, it depends on the task at hand. For ASR it is often around 20 - 40 ms. On a 16000Hz sampling rate it generate frames with 320 - 420 data points. Hop/stride is the window shift between 2 analysis, half the window length size is also often used but not a absolute rule, window stride determine the temporal precision. For 10 - 20 ms window-stride, each frame starts 160 - 210 points after the previous window.
The n_fft is an other parameter, it is the number of data point used to process the Fourier transform. n_fft determine the frequency precision of the output spectrum. 2048 points means that the FFT will be processed on 2048 data points, output will have 1024 points (Nyquish) so a frequency precision of  7.8Hz with a sampling rate at 16kHz ((16000 / 2) / 1024). To compute 2048 points out a window of 320, FFT does a zero padding at the end to have 2048 points.

**Comment by StuartIanNaylor** [comment]
Yeah my bad as that was just tacked on after wondering what the defaults in Librosa where so bad copy & paste.

Copied from the librosa forum on an answer about frame and stride length and apols for posting as did wonder myself.
I just accepted it was different terminology for essentially the same thing.

Its the first reference I was interested in as there the frame size has an 'overlap' but this is my confusion and question as its not just here but on a google you get quite a variety of proposed sizes.

I get the basis is the phoneme time for that language but even if that changes in some examples also does the ratio and never found any definitive.
Its purely curiosity as have never seen reference to certain languages advising longer or lesser frame sizes?
So it 2* stride just to get (Nyquist) sampling?

I am not disagreeing but been wondering that we seem to just copy these without any definitive source and thought I would just ask?

**Comment by Lokhozt** [comment]
**Its purely curiosity as have never seen reference to certain languages advising longer or lesser frame sizes?**

To my knowledge ... i don't know, it may be, but i didn't work outside Latin and Germanic languages. That's probably a concern for ASR but as far as keyword spotting is concerned i never encountered such mention.

**So it 2* stride just to get (Nyquist) sampling?**

Those parameters are not related. Nyquish states that the signal must be sampled at twice the highest desired frequency. So if you want to have a 0-8000Hz amplitude spectrum (which is the case in ASR), you must sample your signal at at least 16000Hz.

**I am not disagreeing but been wondering that we seem to just copy these without any definitive source and thought I would just ask?**

I tend to experiment and score every parameters involved when building a new model for a project. What might work for a configuration may not work as well when context change: microphone setup, ambient noise, keyword chosen, target speakers (childs, elders, persons with elocution disability ?). Most of the time the parameters match-up but sometime an adaptation is necessary to obtain the best performances. The common values are base-lines obtained through experimentation but in my experience are not an absolute true for every situations.

** 1.0 yet is it worth a try? ** 

Nope, this is still a work in progress. The only module finished is the dataset management block. It is a complete overhaul so i have to redo most of the work as it's meant to be more versatile.
